/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Audio
 #	author : miyako
 #	2017/03/10
 #
 # --------------------------------------------------------------------------------*/



// --- Devices
void AUDIO_DEVICE_LIST(sLONG_PTR *pResult, PackagePtr pParams);

// --- Record
void AUDIO_End_recording(PA_PluginParameters params);
void AUDIO_Begin_recording(PA_PluginParameters params);
void AUDIO_Is_recording(PA_PluginParameters params);

// --- Play
void AUDIO_Open_file(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_CLOSE(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_PLAY(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_PAUSE(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_RESUME(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_STOP(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_Is_playing(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_Get_duration(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_Get_time(sLONG_PTR *pResult, PackagePtr pParams);
void AUDIO_SET_TIME(sLONG_PTR *pResult, PackagePtr pParams);

// --- Convert
void AUDIO_Convert(PA_PluginParameters params);